# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/minitools',
                'doc_host': 'https://butchland.github.io',
                'git_url': 'https://github.com/butchland/minitools',
                'lib_path': 'minitools'},
  'syms': {'minitools.utils': {'minitools.utils.foo': ('utils.html#foo', 'minitools/utils.py')}}}