# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/minitools',
                'doc_host': 'https://butchland.github.io',
                'git_url': 'https://github.com/butchland/minitools',
                'lib_path': 'minitools'},
  'syms': {'minitools.core': {'minitools.core.foo': ('core.html#foo', 'minitools/core.py')}}}