# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/minitools',
                'doc_host': 'https://butchland.github.io',
                'git_url': 'https://github.com/butchland/minitools',
                'lib_path': 'minitools'},
  'syms': { 'minitools.utils': { 'minitools.utils.conv_img_size': ('utils.html#conv_img_size', 'minitools/utils.py'),
                                 'minitools.utils.tconv_img_size': ('utils.html#tconv_img_size', 'minitools/utils.py')}}}