# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_utils.ipynb.

# %% auto 0
__all__ = ['conv_img_size', 'tconv_img_size']

# %% ../nbs/01_utils.ipynb 4
def conv_img_size(w:int, # width/height
                  k:int=3, # kernel size
                  p:int=1, # padding
                  s:int=1, # stride
                  d:int=1, # dilation
                 ): 
    return ((w - d*(k - 1) - 1 + 2*p)//s + 1)

# %% ../nbs/01_utils.ipynb 9
def tconv_img_size(w,k=3,s=1,p=0,d=1,op=0): 
    return ((w - 1) * s - 2 * p + d * (k - 1) + op + 1) 
